//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopZen.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopZenEntities1 : DbContext
    {
        public ShopZenEntities1()
            : base("name=ShopZenEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryTable> CategoryTables { get; set; }
        public virtual DbSet<OrderDetailsTable> OrderDetailsTables { get; set; }
        public virtual DbSet<OrderTable> OrderTables { get; set; }
        public virtual DbSet<ProductTable> ProductTables { get; set; }
        public virtual DbSet<ReviewTable> ReviewTables { get; set; }
        public virtual DbSet<UserTable> UserTables { get; set; }

		public System.Data.Entity.DbSet<ShopZen.ViewModels.LoginViewModel> LoginViewModels { get; set; }

		public System.Data.Entity.DbSet<ShopZen.ViewModels.MainHomeViewModel> MainHomeViewModels { get; set; }
	}
}
